//! Unitframe templates generated by ../unitframes/build_unitframes.py and
//! embedded at build time.  Colours / layout values are @@TOKENS@@ that
//! `install::render` fills in.

pub const PLAYER: &str = "ui_ground_hud_mfd_status_skinned.inc";
pub const TARGET: &str = "ui_ground_hud_targets_skinned.inc";
pub const SECONDARY: &str = "ui_ground_hud_secondary_targets_skinned.inc";
pub const GROUP: &str = "ui_ground_hud_sml_group_window.inc";
pub const PET: &str = "ui_ground_hud_pet.inc";
pub const NAMEPLATES: &str = "ui_ground_hud_all_targets.inc";

pub const PAGES: [&str; 6] = [PLAYER, TARGET, SECONDARY, GROUP, PET, NAMEPLATES];

/// Pick the template text for `file` given the two layout switches.  The
/// player page has inline-buff and role-colour variants, group and pet have
/// role-colour variants; every other page has one template.
pub fn get(file: &str, inline_buffs: bool, role_colors: bool) -> Option<&'static str> {
    Some(match file {
        PLAYER => match (inline_buffs, role_colors) {
            (false, false) => include_str!("../templates/ui_ground_hud_mfd_status_skinned.inc"),
            (false, true) => include_str!("../templates/rolecolors/ui_ground_hud_mfd_status_skinned.inc"),
            (true, false) => include_str!("../templates/inlinebuffs/ui_ground_hud_mfd_status_skinned.inc"),
            (true, true) => include_str!("../templates/inlinebuffs/rolecolors/ui_ground_hud_mfd_status_skinned.inc"),
        },
        GROUP => match role_colors {
            false => include_str!("../templates/ui_ground_hud_sml_group_window.inc"),
            true => include_str!("../templates/rolecolors/ui_ground_hud_sml_group_window.inc"),
        },
        PET => match role_colors {
            false => include_str!("../templates/ui_ground_hud_pet.inc"),
            true => include_str!("../templates/rolecolors/ui_ground_hud_pet.inc"),
        },
        TARGET => include_str!("../templates/ui_ground_hud_targets_skinned.inc"),
        SECONDARY => include_str!("../templates/ui_ground_hud_secondary_targets_skinned.inc"),
        NAMEPLATES => include_str!("../templates/ui_ground_hud_all_targets.inc"),
        _ => return None,
    })
}

/// Stock `ui/ui_styles.inc`, the base the role-colour patch is applied to.
/// Replace the file under templates/stock if the game ships a new one.
pub const STOCK_STYLES: &str = include_str!("../templates/stock/ui_styles.inc");
